# Generated by Django 5.0.3 on 2024-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_course_id_alter_question_id_alter_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
